apiVersion: v1
kind: Secret
metadata:
  name: repo-tfm-auth
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/MVR-96/tfm-gitops-setup.git
  username: MVR-96
  password: ${GITHUB_TOKEN}